name: Build

on: [push]
#on:
#  release:
#    types: [created]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1

    - name: Set Environment Variables
      uses: allenevans/set-env@v1.0.0
      with:
        PACKAGE_NAME: "faster_than_walk"
        PACKAGE_VERSION: "1.9"
        MAIN_MODULE: "src/faster_than_walk.nim"
        TWINE_NON_INTERACTIVE: 1
        CHOOSENIM_NO_ANALYTICS: 1
        PYTHONDONTWRITEBYTECODE: 1
        GITHUB_TOKEN:   ${{ secrets.COMMIT_TOKEN }}
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        #TWINE_REPOSITORY_URL: "https://test.pypi.org/legacy/"
        #TWINE_REPOSITORY: "https://test.pypi.org/legacy/"


    - name: Update Python PIP
      run: pip3 install --quiet --user --upgrade --disable-pip-version-check pip twine


    - name: Clone Nim
      run: |
        git clone -q --depth 1 https://github.com/nim-lang/Nim.git
        echo "::add-path::$PWD/Nim/bin"


    - name: Build Nim (Unix)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        cd Nim
        ./build_all.sh


    - name: Build Nim (Windows)
      if: runner.os == 'Windows'
      run: |
        cd Nim
        ./build_all.bat


    - name: Nimble Refresh
      run: nimble -y refresh


    - name: Nimble Install dependencies
      run: nimble -y install nimpy


    - name: Prepare Folders
      if: runner.os == 'Linux'
      run: mkdir -p dist/lin dist/win dist/mac dist/$PACKAGE_NAME.egg-info


    - name: Prepare Files
      if: runner.os == 'Linux'
      run: |
        touch dist/LICENSE dist/$PACKAGE_NAME.egg-info/zip-safe dist/$PACKAGE_NAME.egg-info/top_level.txt dist/$PACKAGE_NAME.egg-info/requires.txt dist/$PACKAGE_NAME.egg-info/dependency_links.txt
        cp --force $PWD/setup.py          dist/setup.py
        cp --force $PWD/setup.cfg         dist/setup.cfg
        cp --force $PWD/Nim/lib/nimbase.h dist/lin/nimbase.h
        cp --force $PWD/Nim/lib/nimbase.h dist/win/nimbase.h
        cp --force $PWD/Nim/lib/nimbase.h dist/mac/nimbase.h
        cp --force $PWD/PKG-INFO          dist/$PACKAGE_NAME.egg-info/PKG-INFO


    - name: Nim Check
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: nim check --styleCheck:hint $MAIN_MODULE


    - name: Compile Debug & import (Unix)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        nim c --app:lib --out:faster_than_walk.so src/faster_than_walk.nim
        python3 -c "import $PACKAGE_NAME"


    - name: Compile Debug & import (Windows)
      if: runner.os == 'Windows'
      run: |
        nim c --app:lib --out:faster_than_walk.pyd src/faster_than_walk.nim
        python3 -c "import $PACKAGE_NAME"


    - name: Compile (Unix)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        nim compileToC --compileOnly:on --nimcache:dist/lin/ \
        -d:danger -d:release -d:nimBinaryStdFiles -d:noSignalHandler -d:lto \
        --app:lib --opt:speed --cpu:amd64 --forceBuild --compileOnly --tlsEmulation:off \
        --stackTrace:off --exceptions:goto --gc:markAndSweep  --excessiveStackTrace:off \
        $MAIN_MODULE


    - name: Compile (Windows)
      if: runner.os == 'Windows'
      run: |
        nim compileToC --compileOnly:on --nimcache:dist/lin/ \
        -d:danger -d:release -d:nimBinaryStdFiles -d:noSignalHandler -d:lto \
        --app:lib --opt:speed --cpu:amd64 --forceBuild --compileOnly --tlsEmulation:on  \
        --stackTrace:off --exceptions:goto --gc:markAndSweep  --excessiveStackTrace:off \
        src/faster_than_walk.nim


    - name: Clean out
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: rm --force --verbose dist/lin/*.json dist/win/*.json dist/mac/*.json dist/lin/*.o dist/win/*.o dist/mac/*.o


    - name: Compress to ZIP
      if: runner.os == 'Linux'
      run: |
        cd dist
        rm --force --verbose *.zip
        zip -9 -T -v -r $PACKAGE_NAME-$PACKAGE_VERSION.zip *


    - uses: EndBug/add-and-commit@v4
      with:
        add: 'dist'
        author_name: Juan Carlos
        force: true
        message: 'Fully Automated Luxury Python'


    - name: Cache Nim
      uses: actions/cache@v1
      with:
        path: $PWD/Nim/
        key: ${{ runner.os }}-nim
